version: '3.7'
services:
  #postgres service
  postgres:
    #name of the container postgres  
    container_name: db
    # version of postgres 
    image: postgres:latest
    # setting for restart
    restart: on-failure
    environment:
      # creation of a user and a database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devops
    # declaration of ports
    ports:
      - 5321:5321
    #Declaration of the volume
    volumes:
      - ./data:/data/postgres
 
  #flask application
  pyapp:
    #build the dockerfile with the flask app inside
    build: ./
    #depends on the db
    depends_on: 
    - postgres
    #set the volumes
    volumes:
      - ./app:/app
    #set the port
    ports:
      - "80:80"
    #set the variable environment for the db
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_USER=postgres
      - DATABASE_NAME=devops
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
      - FLASK_APP=main.py
