version: '3.7'
services:
  postgres:
    #name of the docker  
    container_name: db
    # version of postgres 
    image: postgres:latest
    # setting for restart
    restart: on-failure
    environment:
      # creation of a user and a database
      POSTGRES_USER: Webservice
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: postgres
      # declaration of ports
    ports:
      - 5432:5432
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
 
  web:
    build: ./
    depends_on: 
    - postgres
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - ADR=postgres
      - USR=Webservice
      - DB=web
      - PAWD=P@ssw0rd
      - PRT=5432
