apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Documents\ECE\ING4 2020-2021\Devops\Dev_ops_SI2_10\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
  - name: "5416"
    port: 5416
    targetPort: 5432
  selector:
    io.kompose.service: postgres
status:
  loadBalancer: {}