apiVersion: v1
kind: Pod

metadata:
  name: db

spec:
  containers:
  - name: db
    env:
    - name: POSTGRES_DB
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    - name: POSTGRES_USER
      value: postgres
    image: postgres:latest
    ports:
    - containerPort: 5432
    resources: {}
  restartPolicy: OnFailure
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres-service
spec:
  ports:
  - name: "5416"
    port: 5416
    targetPort: 5432
  selector:
    name: db
    
status:
  loadBalancer: {}