apiVersion: v1
kind: Service
metadata:
  name: "flask-service"
  namespace: "default"
  labels:
    app: "flask"
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: "flask"
status:
  loadBalancer: {}