apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pyapp
  template:
    metadata:
      labels:
        app: pyapp
  spec:
      containers:
      - name: pyapp
      - env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_NAME
          value: devops
        - name: FLASK_APP
          value: main.py
        - name: DATABASE_PASSWORD
          value: postgres
        - name: DATABASE_PORT
          value: "5432"
        - name: RUN
          value: python3 main.py
        - name: DATABASE_USER
          value: postgres
        image: mypyapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
