---
- hosts: devops_project
  # Run commands as root
  become: true
  # Roles to be executed on these hosts
  roles:
  - role: python/install
    tags: install
  - role: postgres/install
    tags: install
  - role: packages/install
    tags: install
