apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
  labels:
    app: devops
    version: v1
spec:
  selector:
    matchLabels:
      app: devops
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: devops
        version: v1
    spec:
      serviceAccountName: devops
      containers:
      - name: devops
        stdin: true
        tty: true
        resources:
          requests:
            cpu: "200m"
            memory : "500Mi"
          limits:
            cpu: "0.4"
            memory : "701Mi"
        ports:
        - containerPort: 3000
          protocol: TCP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-v1
  labels:
    app: devops-v1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-v1
      version: v1
  template:
    metadata:
      labels:
        app: devops-v1
        version: v1
    spec:
      serviceAccountName: devops-v1
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-v1
  labels:
    account: devops-v1
---
apiVersion: v1
kind: Service
metadata:
  name: devops-v1
  labels:
    app: devops-v1
    service: devops-v1
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: devops-v1