# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Do not pay attention to this parameter
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vm.provider :virtualbox do |vb|
      config.vbguest.auto_update = false
    end
  end

  # Define the VM
  config.vm.define "project_devops" do |server|
    # Specify the Vagrant box to use 
    server.vm.box = "debian/stretch64"
    config.vm.synced_folder ".","/home/vagrant/userapi"
    # Specify the VM ip address
    server.vm.network :private_network, ip: "20.20.20.1"
     # Specify the VM specs when using the Virtualbox provisioner
    server.vm.provider "virtualbox" do |vb|
      vb.name =  "project_devops_server_local"
      # VM RAM in MB
      vb.memory = 2048
      # VM CPUs
      vb.cpus = 1  
    end    
  end
  
  Vagrant.configure("2") do |config|
    # Run Ansible from the Vagrant VM
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

end