Vagrant.configure("2") do |config|

  #Definition de la VM
  config.vm.define "devops_project" do |server|
    server.vm.box = "debian/stretch64"
    config.vm.synced_folder "../../userapi","/home/userapi"
      #Definition du spec de la VM
      server.vm.provider "virtualbox" do |vb|
        virtualbox.name =  "devops_project_local"
        virtualbox.memory = 4096
        virtualbox.cpus = 1
      end

    end

  config.vm.network :private_network, "ip:20.20.20.2"


  #Configurztion de Ansible
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbooks/run.yml"
    ansible.tags = "install"
  end

end