name: Main CI/CD

#CI part
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
          POSTGRES_DB: 'action'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set python version 
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install pip
      run: python -m pip install --upgrade pip

    - name: Install requirements.txt
      run: pip install -r requirements.txt

    - name: Environment variable
      run: |
          export DATABASE_NAME=DevOps
          export DATABASE_USER=postgres
          export DATABASE_PASSWORD=ECE2021
          export DATABASE_PORT=5432
          export DATABASE_HOST=localhost

    - name: Run tests
      run: |
        cd userapi
        pytest test.py


  # CD part
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  