name: Main CI/CD

#CI part
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: userapi
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'ECE2021'
          POSTGRES_DB: 'DevOps'
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set python version 
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install pip
      run: python -m pip install --upgrade pip

    - name: Install requirements.txt
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest test.py

  # CD part
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  